# sonarqube/Dockerfile

FROM sonarsource/sonar-scanner-cli:latest

# Définir le répertoire de travail
WORKDIR /usr/src

# Commande exécutée par défaut (modifiable via docker-compose)
ENTRYPOINT ["sonar-scanner"]
